
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '3', 'Tole 1');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Bharatpur Metropolitan City', '6', 'Tole 2');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Tapli Rural Municipality', '5', 'Tole 3');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Jaljala Rural Municipality', '5', 'Tole 4');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Bharatpur Metropolitan City', '20', 'Tole 5');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '7', 'Tole 6');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Bharatpur Metropolitan City', '18', 'Tole 7');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Modi Rural Municipality', '3', 'Tole 8');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Triyuga Municipality', '7', 'Tole 9');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Modi Rural Municipality', '4', 'Tole 10');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Katari  Municipality', '14', 'Tole 11');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Rautamai Rural Municipality', '7', 'Tole 12');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Khairahani Municipality', '12', 'Tole 13');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Chaudandigadhi Municipality', '10', 'Tole 14');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Parsagadhi Municipality', '6', 'Tole 15');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Belauri Municipality', '4', 'Tole 16');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '16', 'Tole 17');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Dodhara Chandani Municipality', '5', 'Tole 18');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Shuklaphanta Municipality', '3', 'Tole 19');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '12', 'Tole 20');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Udayapurgadhi Rural Municipality', '4', 'Tole 21');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Painyu Rural Municipality', '2', 'Tole 22');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bhimdatta Municipality', '7', 'Tole 23');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Aathbiskot Municipality', '7', 'Tole 24');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Rapti Municipality', '2', 'Tole 25');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Belaka  Municipality', '6', 'Tole 26');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '13', 'Tole 27');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Krishnapur Municipality', '4', 'Tole 28');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Banfikot Rural Municipality', '8', 'Tole 29');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Kalika Municipality', '11', 'Tole 30');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Katari  Municipality', '6', 'Tole 31');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Painyu Rural Municipality', '3', 'Tole 32');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Pratapur Rural Municipality', '3', 'Tole 33');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Musikot Municipality', '3', 'Tole 34');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Tribeni Rural Municipality', '1', 'Tole 35');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Pratapur Rural Municipality', '6', 'Tole 36');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Sani Bheri Rural Municipality', '6', 'Tole 37');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Bardaghat Municipality', '14', 'Tole 38');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Dodhara Chandani Municipality', '6', 'Tole 39');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Pokhariya Municipality', '4', 'Tole 40');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Chaudandigadhi Municipality', '6', 'Tole 41');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Rapti Municipality', '13', 'Tole 42');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '20', 'Tole 43');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Musikot Municipality', '5', 'Tole 44');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Bahudaramai Municipality', '3', 'Tole 45');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Kushma Municipality', '8', 'Tole 46');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Pratapur Rural Municipality', '4', 'Tole 47');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '19', 'Tole 48');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Sarawal Rural Municipality', '3', 'Tole 49');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Ramgram Municipality', '11', 'Tole 50');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Pakahamainpur Rural Municipality', '4', 'Tole 51');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Kalikamai Rural Municipality', '2', 'Tole 52');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Bharatpur Metropolitan City', '25', 'Tole 53');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Limchungbung Rural Municipality', '1', 'Tole 54');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Punarbas Municipality', '4', 'Tole 55');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Katari  Municipality', '1', 'Tole 56');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Katari  Municipality', '13', 'Tole 57');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bhimdatta Municipality', '10', 'Tole 58');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Punarbas Municipality', '2', 'Tole 59');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bhimdatta Municipality', '1', 'Tole 60');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Chhipaharmai Rural Municipality', '1', 'Tole 61');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Khairahani Municipality', '11', 'Tole 62');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Chaurjahari Municipality', '11', 'Tole 63');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Triyuga Municipality', '16', 'Tole 64');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Kalika Municipality', '8', 'Tole 65');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Kushma Municipality', '4', 'Tole 66');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Triyuga Municipality', '11', 'Tole 67');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Pratapur Rural Municipality', '9', 'Tole 68');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Khairahani Municipality', '5', 'Tole 69');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Sakhuwa Prasauni Rural Municipality', '5', 'Tole 70');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Krishnapur Municipality', '3', 'Tole 71');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Shuklaphanta Municipality', '1', 'Tole 72');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '11', 'Tole 73');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Banfikot Rural Municipality', '2', 'Tole 74');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Sani Bheri Rural Municipality', '5', 'Tole 75');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Shuklaphanta Municipality', '6', 'Tole 76');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Triyuga Municipality', '3', 'Tole 77');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Ratnanagar Municipality', '7', 'Tole 78');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'phalebas Municipality', '4', 'Tole 79');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Bihadi Rural Municipality', '1', 'Tole 80');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Krishnapur Municipality', '2', 'Tole 81');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Kushma Municipality', '12', 'Tole 82');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Bharatpur Metropolitan City', '26', 'Tole 83');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Limchungbung Rural Municipality', '5', 'Tole 84');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Ramgram Municipality', '4', 'Tole 85');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Rautamai Rural Municipality', '3', 'Tole 86');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Krishnapur Municipality', '5', 'Tole 87');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Pokhariya Municipality', '2', 'Tole 88');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Modi Rural Municipality', '8', 'Tole 89');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Chhipaharmai Rural Municipality', '4', 'Tole 90');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Chhipaharmai Rural Municipality', '5', 'Tole 91');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Musikot Municipality', '12', 'Tole 92');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Bharatpur Metropolitan City', '16', 'Tole 93');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Chaudandigadhi Municipality', '3', 'Tole 94');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '28', 'Tole 95');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Musikot Municipality', '8', 'Tole 96');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Palhi Nandan Rural Municipality', '5', 'Tole 97');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '30', 'Tole 98');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Ramgram Municipality', '17', 'Tole 99');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Banfikot Rural Municipality', '6', 'Tole 100');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '31', 'Tole 101');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Ratnanagar Municipality', '3', 'Tole 102');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Mahashila Rural Municipality', '4', 'Tole 103');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Bharatpur Metropolitan City', '19', 'Tole 104');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Beldandi Rural Municipality', '1', 'Tole 105');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Jirabhawani Rural Municipality', '1', 'Tole 106');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Dodhara Chandani Municipality', '10', 'Tole 107');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Chaudandigadhi Municipality', '1', 'Tole 108');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Ramgram Municipality', '1', 'Tole 109');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Ratnanagar Municipality', '1', 'Tole 110');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Bardaghat Municipality', '10', 'Tole 111');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Katari  Municipality', '10', 'Tole 112');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Jaljala Rural Municipality', '4', 'Tole 113');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'phalebas Municipality', '1', 'Tole 114');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Jaljala Rural Municipality', '9', 'Tole 115');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Paterwa Sugauli Rural Municipality', '5', 'Tole 116');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Ramgram Municipality', '9', 'Tole 117');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Triyuga Municipality', '15', 'Tole 118');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Bharatpur Metropolitan City', '21', 'Tole 119');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Rapti Municipality', '6', 'Tole 120');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Chaurjahari Municipality', '14', 'Tole 121');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Sani Bheri Rural Municipality', '1', 'Tole 122');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Sani Bheri Rural Municipality', '2', 'Tole 123');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Dhobini Rural Municipality', '2', 'Tole 124');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Musikot Municipality', '14', 'Tole 125');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Musikot Municipality', '13', 'Tole 126');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Sani Bheri Rural Municipality', '9', 'Tole 127');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Dhobini Rural Municipality', '4', 'Tole 128');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bedkot Municipality', '2', 'Tole 129');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Sakhuwa Prasauni Rural Municipality', '2', 'Tole 130');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Ratnanagar Municipality', '12', 'Tole 131');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Katari  Municipality', '2', 'Tole 132');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Chhipaharmai Rural Municipality', '3', 'Tole 133');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Thori Rural Municipality', '2', 'Tole 134');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Tribeni Rural Municipality', '6', 'Tole 135');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'phalebas Municipality', '5', 'Tole 136');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Bharatpur Metropolitan City', '10', 'Tole 137');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bedkot Municipality', '10', 'Tole 138');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Khairahani Municipality', '3', 'Tole 139');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Madi Municipality', '6', 'Tole 140');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Rautamai Rural Municipality', '4', 'Tole 141');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Katari  Municipality', '8', 'Tole 142');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Krishnapur Municipality', '7', 'Tole 143');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'phalebas Municipality', '3', 'Tole 144');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Belaka  Municipality', '7', 'Tole 145');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Kalika Municipality', '3', 'Tole 146');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Kalika Municipality', '4', 'Tole 147');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Krishnapur Municipality', '6', 'Tole 148');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Ratnanagar Municipality', '11', 'Tole 149');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Belaka  Municipality', '8', 'Tole 150');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Jagarnathpur Rural Municipality', '5', 'Tole 151');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Pratapur Rural Municipality', '1', 'Tole 152');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Sarawal Rural Municipality', '7', 'Tole 153');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Jirabhawani Rural Municipality', '5', 'Tole 154');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Tribeni Rural Municipality', '9', 'Tole 155');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bedkot Municipality', '6', 'Tole 156');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Pakahamainpur Rural Municipality', '5', 'Tole 157');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Rautamai Rural Municipality', '2', 'Tole 158');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Chaurjahari Municipality', '5', 'Tole 159');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Bahudaramai Municipality', '1', 'Tole 160');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Madi Municipality', '7', 'Tole 161');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Madi Municipality', '2', 'Tole 162');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Shuklaphanta Municipality', '5', 'Tole 163');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Bardaghat Municipality', '13', 'Tole 164');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Ramgram Municipality', '6', 'Tole 165');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Ratnanagar Municipality', '6', 'Tole 166');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Bahudaramai Municipality', '7', 'Tole 167');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Chaudandigadhi Municipality', '9', 'Tole 168');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'phalebas Municipality', '9', 'Tole 169');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Aathbiskot Municipality', '9', 'Tole 170');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Jaljala Rural Municipality', '3', 'Tole 171');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Ichchhyakamana Rural Municipality', '7', 'Tole 172');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Bharatpur Metropolitan City', '23', 'Tole 173');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Ratnanagar Municipality', '15', 'Tole 174');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Madi Municipality', '3', 'Tole 175');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Bahudaramai Municipality', '8', 'Tole 176');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Parsagadhi Municipality', '5', 'Tole 177');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Ramgram Municipality', '8', 'Tole 178');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Modi Rural Municipality', '7', 'Tole 179');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Pakahamainpur Rural Municipality', '1', 'Tole 180');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Sunwal Municipality', '9', 'Tole 181');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Chaurjahari Municipality', '8', 'Tole 182');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Ramgram Municipality', '12', 'Tole 183');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Laljhadi Rural Municipality', '3', 'Tole 184');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bhimdatta Municipality', '15', 'Tole 185');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Sani Bheri Rural Municipality', '4', 'Tole 186');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Aathbiskot Municipality', '13', 'Tole 187');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Palhi Nandan Rural Municipality', '4', 'Tole 188');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Aathbiskot Municipality', '5', 'Tole 189');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '9', 'Tole 190');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bedkot Municipality', '5', 'Tole 191');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Udayapurgadhi Rural Municipality', '2', 'Tole 192');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Bihadi Rural Municipality', '5', 'Tole 193');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Aathbiskot Municipality', '10', 'Tole 194');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Susta Rural Municipality', '2', 'Tole 195');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Parsagadhi Municipality', '4', 'Tole 196');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Ratnanagar Municipality', '10', 'Tole 197');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Kushma Municipality', '3', 'Tole 198');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Katari  Municipality', '12', 'Tole 199');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Sarawal Rural Municipality', '5', 'Tole 200');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Susta Rural Municipality', '3', 'Tole 201');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bhimdatta Municipality', '5', 'Tole 202');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Rautamai Rural Municipality', '5', 'Tole 203');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Sakhuwa Prasauni Rural Municipality', '6', 'Tole 204');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Sunwal Municipality', '12', 'Tole 205');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Rapti Municipality', '1', 'Tole 206');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Tapli Rural Municipality', '3', 'Tole 207');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Ramgram Municipality', '2', 'Tole 208');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Chaurjahari Municipality', '10', 'Tole 209');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Bardaghat Municipality', '2', 'Tole 210');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Bharatpur Metropolitan City', '2', 'Tole 211');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Aathbiskot Municipality', '3', 'Tole 212');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Belaka  Municipality', '4', 'Tole 213');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Tribeni Rural Municipality', '2', 'Tole 214');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Bharatpur Metropolitan City', '22', 'Tole 215');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Ramgram Municipality', '5', 'Tole 216');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Dodhara Chandani Municipality', '7', 'Tole 217');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Painyu Rural Municipality', '4', 'Tole 218');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bedkot Municipality', '8', 'Tole 219');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Udayapurgadhi Rural Municipality', '1', 'Tole 220');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Ramgram Municipality', '14', 'Tole 221');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Rautamai Rural Municipality', '8', 'Tole 222');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Ramgram Municipality', '10', 'Tole 223');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Belaka  Municipality', '2', 'Tole 224');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Musikot Municipality', '7', 'Tole 225');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bedkot Municipality', '7', 'Tole 226');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Paterwa Sugauli Rural Municipality', '1', 'Tole 227');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Rapti Municipality', '10', 'Tole 228');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Belauri Municipality', '5', 'Tole 229');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Kushma Municipality', '2', 'Tole 230');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Thori Rural Municipality', '5', 'Tole 231');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Susta Rural Municipality', '5', 'Tole 232');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Painyu Rural Municipality', '1', 'Tole 233');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Bharatpur Metropolitan City', '7', 'Tole 234');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Pokhariya Municipality', '8', 'Tole 235');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Ratnanagar Municipality', '9', 'Tole 236');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Bharatpur Metropolitan City', '27', 'Tole 237');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Laljhadi Rural Municipality', '5', 'Tole 238');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '29', 'Tole 239');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Ichchhyakamana Rural Municipality', '5', 'Tole 240');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Bharatpur Metropolitan City', '15', 'Tole 241');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Shuklaphanta Municipality', '9', 'Tole 242');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Udayapurgadhi Rural Municipality', '7', 'Tole 243');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Punarbas Municipality', '1', 'Tole 244');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Palhi Nandan Rural Municipality', '1', 'Tole 245');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Chaurjahari Municipality', '4', 'Tole 246');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Kushma Municipality', '7', 'Tole 247');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Pokhariya Municipality', '3', 'Tole 248');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Triyuga Municipality', '10', 'Tole 249');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Ramgram Municipality', '13', 'Tole 250');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Ratnanagar Municipality', '14', 'Tole 251');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Bharatpur Metropolitan City', '13', 'Tole 252');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Punarbas Municipality', '7', 'Tole 253');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Belauri Municipality', '8', 'Tole 254');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Limchungbung Rural Municipality', '2', 'Tole 255');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Chaudandigadhi Municipality', '4', 'Tole 256');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Belauri Municipality', '1', 'Tole 257');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Sunwal Municipality', '13', 'Tole 258');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Parsagadhi Municipality', '9', 'Tole 259');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Bindabasini Rural Municipality', '2', 'Tole 260');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Tapli Rural Municipality', '1', 'Tole 261');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Jaljala Rural Municipality', '8', 'Tole 262');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bhimdatta Municipality', '4', 'Tole 263');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bhimdatta Municipality', '3', 'Tole 264');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'phalebas Municipality', '7', 'Tole 265');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Bardaghat Municipality', '9', 'Tole 266');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bhimdatta Municipality', '2', 'Tole 267');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Bardaghat Municipality', '15', 'Tole 268');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Krishnapur Municipality', '9', 'Tole 269');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bhimdatta Municipality', '17', 'Tole 270');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Dodhara Chandani Municipality', '1', 'Tole 271');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bhimdatta Municipality', '9', 'Tole 272');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Jaljala Rural Municipality', '1', 'Tole 273');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Katari  Municipality', '11', 'Tole 274');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Katari  Municipality', '3', 'Tole 275');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Punarbas Municipality', '6', 'Tole 276');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Jirabhawani Rural Municipality', '3', 'Tole 277');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '22', 'Tole 278');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'phalebas Municipality', '8', 'Tole 279');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Bharatpur Metropolitan City', '9', 'Tole 280');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Kalika Municipality', '9', 'Tole 281');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Khairahani Municipality', '4', 'Tole 282');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Jagarnathpur Rural Municipality', '4', 'Tole 283');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Katari  Municipality', '9', 'Tole 284');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Dodhara Chandani Municipality', '8', 'Tole 285');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Khairahani Municipality', '13', 'Tole 286');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Paterwa Sugauli Rural Municipality', '3', 'Tole 287');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Dodhara Chandani Municipality', '3', 'Tole 288');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Painyu Rural Municipality', '5', 'Tole 289');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Triyuga Municipality', '1', 'Tole 290');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Kalikamai Rural Municipality', '4', 'Tole 291');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bhimdatta Municipality', '8', 'Tole 292');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Sani Bheri Rural Municipality', '10', 'Tole 293');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Sani Bheri Rural Municipality', '11', 'Tole 294');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Bahudaramai Municipality', '4', 'Tole 295');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '5', 'Tole 296');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Rapti Municipality', '12', 'Tole 297');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Rautamai Rural Municipality', '6', 'Tole 298');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '32', 'Tole 299');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Chaurjahari Municipality', '3', 'Tole 300');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Modi Rural Municipality', '2', 'Tole 301');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Tribeni Rural Municipality', '10', 'Tole 302');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Bharatpur Metropolitan City', '29', 'Tole 303');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Aathbiskot Municipality', '6', 'Tole 304');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Chaurjahari Municipality', '7', 'Tole 305');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Shuklaphanta Municipality', '8', 'Tole 306');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Jagarnathpur Rural Municipality', '3', 'Tole 307');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Musikot Municipality', '1', 'Tole 308');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Banfikot Rural Municipality', '7', 'Tole 309');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Bahudaramai Municipality', '5', 'Tole 310');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Madi Municipality', '5', 'Tole 311');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Ratnanagar Municipality', '16', 'Tole 312');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Dodhara Chandani Municipality', '2', 'Tole 313');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Belaka  Municipality', '9', 'Tole 314');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Rapti Municipality', '8', 'Tole 315');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Bardaghat Municipality', '4', 'Tole 316');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Bardaghat Municipality', '3', 'Tole 317');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Pratapur Rural Municipality', '5', 'Tole 318');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Shuklaphanta Municipality', '4', 'Tole 319');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Ramgram Municipality', '15', 'Tole 320');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Banfikot Rural Municipality', '3', 'Tole 321');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Kushma Municipality', '9', 'Tole 322');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Modi Rural Municipality', '5', 'Tole 323');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Pakahamainpur Rural Municipality', '3', 'Tole 324');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Punarbas Municipality', '5', 'Tole 325');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Sani Bheri Rural Municipality', '7', 'Tole 326');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Shuklaphanta Municipality', '12', 'Tole 327');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Mahashila Rural Municipality', '5', 'Tole 328');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Bardaghat Municipality', '16', 'Tole 329');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Tribeni Rural Municipality', '3', 'Tole 330');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Chaudandigadhi Municipality', '2', 'Tole 331');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '1', 'Tole 332');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Jirabhawani Rural Municipality', '4', 'Tole 333');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Dodhara Chandani Municipality', '9', 'Tole 334');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Bardaghat Municipality', '11', 'Tole 335');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Ramgram Municipality', '3', 'Tole 336');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Triyuga Municipality', '6', 'Tole 337');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Kalika Municipality', '5', 'Tole 338');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Palhi Nandan Rural Municipality', '6', 'Tole 339');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '10', 'Tole 340');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Ichchhyakamana Rural Municipality', '4', 'Tole 341');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Rapti Municipality', '7', 'Tole 342');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Jagarnathpur Rural Municipality', '2', 'Tole 343');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Jaljala Rural Municipality', '2', 'Tole 344');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Jirabhawani Rural Municipality', '2', 'Tole 345');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Kushma Municipality', '5', 'Tole 346');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Banfikot Rural Municipality', '9', 'Tole 347');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Pokhariya Municipality', '5', 'Tole 348');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Ichchhyakamana Rural Municipality', '6', 'Tole 349');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Pokhariya Municipality', '1', 'Tole 350');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Belauri Municipality', '7', 'Tole 351');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Parsagadhi Municipality', '3', 'Tole 352');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Punarbas Municipality', '8', 'Tole 353');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Kalikamai Rural Municipality', '3', 'Tole 354');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Belaka  Municipality', '3', 'Tole 355');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bhimdatta Municipality', '14', 'Tole 356');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Chhipaharmai Rural Municipality', '2', 'Tole 357');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '23', 'Tole 358');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Chaurjahari Municipality', '13', 'Tole 359');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Ratnanagar Municipality', '13', 'Tole 360');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Sarawal Rural Municipality', '6', 'Tole 361');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Paterwa Sugauli Rural Municipality', '2', 'Tole 362');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '14', 'Tole 363');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'phalebas Municipality', '11', 'Tole 364');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Katari  Municipality', '4', 'Tole 365');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Shuklaphanta Municipality', '2', 'Tole 366');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Susta Rural Municipality', '4', 'Tole 367');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bhimdatta Municipality', '18', 'Tole 368');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '8', 'Tole 369');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Ichchhyakamana Rural Municipality', '2', 'Tole 370');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Bharatpur Metropolitan City', '17', 'Tole 371');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Punarbas Municipality', '10', 'Tole 372');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Tribeni Rural Municipality', '7', 'Tole 373');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Bharatpur Metropolitan City', '28', 'Tole 374');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Modi Rural Municipality', '6', 'Tole 375');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Bihadi Rural Municipality', '2', 'Tole 376');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Triyuga Municipality', '13', 'Tole 377');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Kalika Municipality', '7', 'Tole 378');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Laljhadi Rural Municipality', '4', 'Tole 379');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Tapli Rural Municipality', '4', 'Tole 380');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '24', 'Tole 381');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Sunwal Municipality', '1', 'Tole 382');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Ramgram Municipality', '16', 'Tole 383');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Sani Bheri Rural Municipality', '8', 'Tole 384');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Beldandi Rural Municipality', '3', 'Tole 385');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Ratnanagar Municipality', '8', 'Tole 386');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Bharatpur Metropolitan City', '11', 'Tole 387');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Musikot Municipality', '4', 'Tole 388');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Udayapurgadhi Rural Municipality', '6', 'Tole 389');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Shuklaphanta Municipality', '10', 'Tole 390');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bhimdatta Municipality', '16', 'Tole 391');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Banfikot Rural Municipality', '10', 'Tole 392');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Mahashila Rural Municipality', '3', 'Tole 393');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Punarbas Municipality', '9', 'Tole 394');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Bardaghat Municipality', '8', 'Tole 395');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Chaurjahari Municipality', '6', 'Tole 396');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Jagarnathpur Rural Municipality', '1', 'Tole 397');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Laljhadi Rural Municipality', '1', 'Tole 398');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '17', 'Tole 399');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Aathbiskot Municipality', '14', 'Tole 400');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Kushma Municipality', '11', 'Tole 401');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Limchungbung Rural Municipality', '4', 'Tole 402');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Madi Municipality', '4', 'Tole 403');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Ramgram Municipality', '7', 'Tole 404');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Bharatpur Metropolitan City', '3', 'Tole 405');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Kushma Municipality', '13', 'Tole 406');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Bihadi Rural Municipality', '6', 'Tole 407');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Bharatpur Metropolitan City', '8', 'Tole 408');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Bindabasini Rural Municipality', '4', 'Tole 409');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'phalebas Municipality', '2', 'Tole 410');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bedkot Municipality', '1', 'Tole 411');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '25', 'Tole 412');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'phalebas Municipality', '6', 'Tole 413');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Pokhariya Municipality', '6', 'Tole 414');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Mahashila Rural Municipality', '1', 'Tole 415');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Sunwal Municipality', '6', 'Tole 416');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Kalika Municipality', '1', 'Tole 417');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Punarbas Municipality', '3', 'Tole 418');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Beldandi Rural Municipality', '2', 'Tole 419');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Limchungbung Rural Municipality', '3', 'Tole 420');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Aathbiskot Municipality', '1', 'Tole 421');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Ramgram Municipality', '18', 'Tole 422');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Rapti Municipality', '4', 'Tole 423');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Aathbiskot Municipality', '4', 'Tole 424');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Chaudandigadhi Municipality', '8', 'Tole 425');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Bardaghat Municipality', '12', 'Tole 426');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Bardaghat Municipality', '5', 'Tole 427');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Ratnanagar Municipality', '5', 'Tole 428');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Pokhariya Municipality', '9', 'Tole 429');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Udayapurgadhi Rural Municipality', '5', 'Tole 430');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Rapti Municipality', '11', 'Tole 431');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Triyuga Municipality', '8', 'Tole 432');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '2', 'Tole 433');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '6', 'Tole 434');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Tapli Rural Municipality', '2', 'Tole 435');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Mahashila Rural Municipality', '2', 'Tole 436');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Bindabasini Rural Municipality', '5', 'Tole 437');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Bardaghat Municipality', '6', 'Tole 438');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Pratapur Rural Municipality', '7', 'Tole 439');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Thori Rural Municipality', '1', 'Tole 440');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Chaudandigadhi Municipality', '7', 'Tole 441');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bhimdatta Municipality', '12', 'Tole 442');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Painyu Rural Municipality', '6', 'Tole 443');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Bharatpur Metropolitan City', '4', 'Tole 444');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Tribeni Rural Municipality', '8', 'Tole 445');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '4', 'Tole 446');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Triyuga Municipality', '5', 'Tole 447');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Musikot Municipality', '6', 'Tole 448');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Aathbiskot Municipality', '2', 'Tole 449');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Belauri Municipality', '9', 'Tole 450');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Khairahani Municipality', '1', 'Tole 451');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '21', 'Tole 452');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Rapti Municipality', '3', 'Tole 453');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Bihadi Rural Municipality', '4', 'Tole 454');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Madi Municipality', '1', 'Tole 455');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bhimdatta Municipality', '6', 'Tole 456');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Pratapur Rural Municipality', '2', 'Tole 457');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Belauri Municipality', '10', 'Tole 458');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Parsagadhi Municipality', '7', 'Tole 459');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Shuklaphanta Municipality', '7', 'Tole 460');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Thori Rural Municipality', '4', 'Tole 461');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Sarawal Rural Municipality', '1', 'Tole 462');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Birgunj Metropolitan City', '27', 'Tole 463');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Kalika Municipality', '10', 'Tole 464');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bhimdatta Municipality', '19', 'Tole 465');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Madi Municipality', '9', 'Tole 466');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Belauri Municipality', '2', 'Tole 467');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Kalikamai Rural Municipality', '5', 'Tole 468');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bhimdatta Municipality', '11', 'Tole 469');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Painyu Rural Municipality', '7', 'Tole 470');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Chaudandigadhi Municipality', '5', 'Tole 471');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Bardaghat Municipality', '7', 'Tole 472');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Madi Municipality', '8', 'Tole 473');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Laljhadi Rural Municipality', '2', 'Tole 474');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Banfikot Rural Municipality', '4', 'Tole 475');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Bindabasini Rural Municipality', '3', 'Tole 476');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Chaurjahari Municipality', '9', 'Tole 477');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Kushma Municipality', '1', 'Tole 478');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Rapti Municipality', '5', 'Tole 479');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Sunwal Municipality', '11', 'Tole 480');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Belauri Municipality', '3', 'Tole 481');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(55, 'Sunwal Municipality', '2', 'Tole 482');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Modi Rural Municipality', '1', 'Tole 483');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Aathbiskot Municipality', '12', 'Tole 484');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Jagarnathpur Rural Municipality', '6', 'Tole 485');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Punarbas Municipality', '11', 'Tole 486');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Bhimdatta Municipality', '13', 'Tole 487');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(44, 'Kushma Municipality', '6', 'Tole 488');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Khairahani Municipality', '2', 'Tole 489');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(76, 'Krishnapur Municipality', '8', 'Tole 490');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Dhobini Rural Municipality', '1', 'Tole 491');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(67, 'Musikot Municipality', '10', 'Tole 492');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Parsagadhi Municipality', '8', 'Tole 493');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Udayapurgadhi Rural Municipality', '3', 'Tole 494');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Triyuga Municipality', '9', 'Tole 495');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Sakhuwa Prasauni Rural Municipality', '4', 'Tole 496');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Bharatpur Metropolitan City', '1', 'Tole 497');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(24, 'Khairahani Municipality', '7', 'Tole 498');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(14, 'Triyuga Municipality', '14', 'Tole 499');
INSERT IGNORE INTO Address(district_id, municipality, ward, tole) VALUES(18, 'Bahudaramai Municipality', '2', 'Tole 500');
