INSERT INTO Profession(profession_name) VALUES
('Teacher'),
('Engineer'),
('Doctor'),
('Nurse'),
('Farmer'),
('Government Officer'),
('Police Officer'),
('Army Officer'),
('Lawyer'),
('Accountant'),
('Business'),
('Driver'),
('Laborer'),
('Journalist'),
('Pharmacist'),
('Lab technician'),
('pilot');